name: 06 Context
on:
    push:
    workflow_dispatch:
jobs:
    echo-data:
        runs-on: ubuntu-latest
        name: Echo GitHub Context Data
        steps:
            - name: Echo GitHub Repository Name
              run: echo "Repository Name: ${{ github.repository }}"
            - name: Echo GitHub Event Name
              run: echo "Event Name: ${{ github.event_name }}"
            - name: Echo GitHub SHA
              run: echo "Commit SHA: ${{ github.sha }}"
            - name: Echo GitHub Actor
              run: echo "Actor: ${{ github.actor }}"
            - name: Echo GitHub Ref
              run: echo "Git Reference: ${{ github.ref }}"
            - name: Echo GitHub Workflow
              run: echo "Workflow Name: ${{ github.workflow }}"
            - name: Echo GitHub Job
              run: echo "Job Name: ${{ github.job }}"
            - name: Echo GitHub Run ID
              run: echo "Run ID: ${{ github.run_id }}"
            - name: Retrieve Variable
              run: echo "Custom Variable: ${{ vars.CUSTOM_VAR }}"