name: 06 Context
run-name: 06 - Context | DEBUG - ${{ inputs.debug }}
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug mode"
        required: false
        type: boolean
        default: false
env:
  MY_WORKFLOW_VAR: "global"
  MY_OVERWRITTEN_VAR: "global"
jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: "job"
      MY_OVERWRITTEN_VAR: "job"

    name: Echo GitHub Context Data
    steps:
      - name: Echo GitHub Repository Name
        run: |
          echo 'Repository Name: ${{ github.repository }}'
      - name: Echo GitHub Event Name
        run: |
          echo "Event Name: ${{ github.event_name }}"
      - name: Echo GitHub SHA
        run: |
          echo "Commit SHA: ${{ github.sha }}"
      - name: Echo GitHub Actor
        run: |
          echo "Actor: ${{ github.actor }}"
      - name: Echo GitHub Ref
        run: |
          echo "Git Reference: ${{ github.ref }}"
      - name: Echo GitHub Workflow
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
      - name: Echo GitHub Job
        run: |
          echo "Job Name: ${{ github.job }}"
      - name: Echo GitHub Run ID
        run: |
          echo "Run ID: ${{ github.run_id }}"
      - name: Retrieve Variable
        run: |
          echo "Custom Variable: ${{ vars.CUSTOM_VAR }}"
      - name: Echo Workflow Environment Variable
        run: |
          echo "Environment Variable MY_WORKFLOW_VAR: ${{ env.MY_WORKFLOW_VAR }}"
      - name: Echo Overwritten Environment Variable
        run: |
          echo "Overwritten Environment Variable MY_OVERWRITTEN_VAR: ${{ env.MY_OVERWRITTEN_VAR }}"
      - name: Echo Environment Variable
        run: |
          echo "Environment Variable MY_JOB_VAR: ${{ env.MY_JOB_VAR }}"
      - name: Echo Overwritten Environment Variable
        run: |
          echo "Overwritten Environment Variable MY_OVERWRITTEN_VAR: ${{ env.MY_OVERWRITTEN_VAR }}"
