name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      status-build:
        description: "Emulate the status of a build"
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{steps.build.outputs.status}}
    steps:
      - name: Print GITHUB_OUTPUT
        run: |
          echo "$GITHUB_OUTPUT"
      - name: build
        id: build
        run: echo "<build-status>${{ inputs.build-status }}">> "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{needs.build.outputs.build-status=='success'}}
    steps:
      - name: deploy
        run: echo "Deploying"
