name: 17 - Custom Actions - Composite
run-name: 17-1- Custom Actions - JS
on:
    workflow_dispatch:
        inputs:
            target-env:
                description: Environment
                type: choice
                options:
                    - dev
                    - prod

env:
    working-directory: ./17-custom-actions/reactapp
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{env.working-directory}}
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Setup Node and NPM dependencies
              uses: ./github/actions/composite-cache-deps
              with:
                  node-version: 20.x
                  work-dir: ${{env.working-directory}}
                  target-env: ${{inputs.target-env}}
            - name: tests
              run: npm run tests
              working-directory: ${{env.working-directory}}
            - name: build
              run: npm run build
              working-directory: ${{env.working-directory}}
