name: 17-2- Custom Actions - JS
run-name: 17-2- Custom Actions - JS
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Check for dependency updates
              uses: ./github/actions/js-dependency-update
            # - name: tests
            #   run: npm run tests
            #   working-directory: ${{env.working-directory}}
            # - name: build
            #   run: npm run build
            #   working-directory: ${{env.working-directory}}
