name: 18-3 Reusable Workflow

on:
    workflow_dispatch:

jobs:
    deploy:
        uses: ./.github/workflows/18.1-reusable-workflows.yaml@main
        with:
            target-directory: dummy-dir
    e2e-test:
        # uses: <owner>/<repo>/.github/workflows/<workflow_name>
        uses: jivfur/github-actions-course-example-e2e/.github/workflows/e2e.yaml@main
        secrets:
            access-token: ${{secrets.GH_TOKEN}}
